task: object_detection
seed: 42
output_dir: outputs_bigbatch

model:
  weights: yolov8n.pt

data:
  yaml: coco128.yaml
  imgsz: 640
  batch: 16     # batch doubl√©

train:
  epochs: 20
  lr0: 0.005
  weight_decay: 0.0005
  patience: 10

device: cpu
