task: cv_classification
seed: 42
output_dir: outputs_tiny_aug

data:
  dataset: imagefolder
  root: ./data/tiny-imagenet-200/train
  img_size: 64
  batch_size: 128
  num_workers: 2
  val_split: 0.1

augment:
  stronger: true     # <- Active les transformations agressives

model:
  arch: resnet18
  pretrained: true
  freeze_backbone: false

train:
  epochs: 30
  optimizer: adamw
  lr: 5.0e-4
  weight_decay: 1.0e-2
  momentum: 0.9
  scheduler: cosine
  t_max: 30

early_stopping:
  patience: 7
  min_delta: 0.0
